# 第五章 pandas 入门 

In [1]:
import pandas as pd 

## 5.1 pandas 的数据结构介绍

### Series

In [2]:
obj = pd.Series([4,7,-5,3])

obj

0    4
1    7
2   -5
3    3
dtype: int64

In [3]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [4]:
obj.value_counts

<bound method IndexOpsMixin.value_counts of 0    4
1    7
2   -5
3    3
dtype: int64>

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
# 对各个数据点进行标记的索引

obj2 = pd.Series([4,7,-5,3], index=['d','b','a','c'])

obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [7]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [8]:
obj2['a']

-5

In [10]:
obj2['d']=6

obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [11]:
obj2[['c','a','d']]

c    3
a   -5
d    6
dtype: int64

In [12]:
obj2[obj2>0]

d    6
b    7
c    3
dtype: int64

In [13]:
obj2*2

d    12
b    14
a   -10
c     6
dtype: int64

In [14]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [15]:
import numpy as np

np.exp(obj2)  # e^(X)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

 可以将 Series 看成是一个定长的有序字典 

In [16]:
'b' in obj2

True

In [17]:
'e' in obj2

False

In [19]:
# 通过字典创建 Series 

sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

obj3 = pd.Series(sdata)

obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

如果只传入一个字典， 结果是 Series 中的索引就是原 字典的 key 

可以传入排好的字典的 key 来改变顺序

In [20]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

obj4 = pd.Series(sdata, index= states)

obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

isnull notnull 可以 用于检测缺失数据

In [21]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [22]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [23]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

Series 最重要的功能是：

根据运算的索引标签自动对齐数据

In [24]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [25]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [26]:
obj3+obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

Series 对象 及其 索引都有一个 name 属性 

In [29]:
obj4.name ='population'

obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [31]:
obj4.index.name ='state'

obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [32]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [33]:
obj.index =['Bob','Steve','Jeff','Ryan']

obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

## DataFrame 

In [35]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [36]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

指定顺序进行排列

In [38]:
pd.DataFrame(data, columns=['year','state','pop'])


year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [39]:
# columns 调整位置 
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four',
                             'five', 'six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [40]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [41]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [42]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [43]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

列可以通过赋值的方式进行修改 

In [44]:
frame2.debt =16.5

In [45]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [46]:
frame2.debt=np.arange(6)

frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4
six    2003  Nevada  3.2     5

In [47]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two','four','five'])

frame2.debt=val

frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

为不存在的列赋值会创建一个新列

In [48]:
frame2['eastern']= frame2.state=='Ohio'

frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [50]:
del frame2.eastern

AttributeError: eastern

In [51]:
del frame2['eastern']

In [52]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [53]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

嵌套字典 

In [54]:

pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

frame3=pd.DataFrame(pop)

frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

对 DataFrame 进行转置 （交换行和列）

In [55]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [56]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [57]:
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [58]:
# 明确指明索引 

pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [59]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [60]:

pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}

pdata

{'Ohio': 2001    1.7
 2002    3.6
 Name: Ohio, dtype: float64, 'Nevada': 2001    2.4
 2002    2.9
 Name: Nevada, dtype: float64}

In [61]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

设置 DataFrame 的index 和 columns 的 name 属性 

In [62]:
frame3 

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [64]:
frame3.index.name ='year'

frame3.columns.name = 'states'

frame3

states  Nevada  Ohio
year                
2001       2.4   1.7
2002       2.9   3.6
2000       NaN   1.5

In [65]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [66]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [67]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

## 索引对象 

In [68]:
obj = pd.Series(range(3), index =['a','b','c'])

obj

a    0
b    1
c    2
dtype: int64

In [69]:
index = obj.index 

index

Index(['a', 'b', 'c'], dtype='object')

In [70]:
index[1:]

Index(['b', 'c'], dtype='object')

index 对象不可改变， 不能对其修改 

In [72]:
index[1]='d'

TypeError: Index does not support mutable operations

不可变 使得 index 对象在多个数据结构之间安全共享 

In [73]:
labels = pd.Index(np.arange(3))

labels

Int64Index([0, 1, 2], dtype='int64')

In [74]:
obj2 = pd.Series([-1.5, -2.5, 0], index = labels)

obj2

0   -1.5
1   -2.5
2    0.0
dtype: float64

In [75]:
obj2.index is labels

True

In [76]:
frame3

states  Nevada  Ohio
year                
2001       2.4   1.7
2002       2.9   3.6
2000       NaN   1.5

In [77]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='states')

In [78]:
'Ohio' in frame3.columns

True

In [79]:
2001 in frame3.index

True

In [80]:
2003 in frame3.index

False

pandas 的 index 可以包含重复的标签 

In [81]:
dup_labels = pd.Index(['foo','foo', 'bar','bar'])

dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

## 5.2 基本功能

### reindex 

In [82]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index =['d','b','a','c'])

obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [83]:
obj2 = obj.reindex(['a','b','c','d','e'])

obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

对于时间序列这样的有序数据

重新索引可能需要做一些插值处理 

method 方法 可以做到 填充 

In [84]:
obj3 = pd.Series(['blue','purple','yellow'], index =[0,2,4])

obj3

0      blue
2    purple
4    yellow
dtype: object

In [86]:
obj3.reindex(range(6), method='ffill')


0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [87]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])

frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [88]:
frame2= frame.reindex(['a','b','c','d'])

frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

列可以用 columns 关键字重新所用

In [89]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [90]:
states=['Texas','Utah','California']

frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

## 丢弃指定轴上的 项

In [91]:
obj = pd.Series(np.arange(5), index= ['a','b','c','d','e'])

obj

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [92]:
new_obj = obj.drop('c')

In [93]:
new_obj

a    0
b    1
d    3
e    4
dtype: int32

In [95]:
obj.drop(['d','c'])



a    0
b    1
e    4
dtype: int32

对于 pd.DataFrame 可以删除任意轴上的索引值 

In [96]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [97]:
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [98]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [99]:
data.drop(['two','four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

###  就地修改 不会返回新的对象 

In [100]:
obj

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [102]:
obj.drop('c', inplace=True)
obj

a    0
b    1
d    3
e    4
dtype: int32

## 索引， 选取， 和 过滤 

In [103]:
obj = pd.Series(np.arange(4), index = ['a','b','c','d'])

obj

a    0
b    1
c    2
d    3
dtype: int32

In [104]:
obj['b']

1

In [105]:
obj[1]

1

In [106]:
obj[2:4]

c    2
d    3
dtype: int32

In [107]:
obj[['b','a','d']]

b    1
a    0
d    3
dtype: int32

In [108]:
obj[[1,3]]

b    1
d    3
dtype: int32

In [109]:
obj[obj<2]

a    0
b    1
dtype: int32

利用标签的切片运算与普通的 Python 切片运算是不同的 包含末端

In [110]:
obj

a    0
b    1
c    2
d    3
dtype: int32

In [111]:
obj['b':'c']

b    1
c    2
dtype: int32

In [112]:
obj['b':'c']=5

obj

a    0
b    5
c    5
d    3
dtype: int32

用一个值 或者 序列对 pd.DataFrame 进行索引即使获取一个或者多个列 

In [113]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

data 

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [114]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [115]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

索引的特殊情况

通过切片或者布尔型数组选取数据

In [116]:
data 

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [117]:
data[:2]  # 单一数字 行 

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [118]:
data<5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [119]:
data[data<5]

one  two  three  four
Ohio      0.0  1.0    2.0   3.0
Colorado  4.0  NaN    NaN   NaN
Utah      NaN  NaN    NaN   NaN
New York  NaN  NaN    NaN   NaN

In [121]:
data[data<5]=5

data 

one  two  three  four
Ohio        5    5      5     5
Colorado    5    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### 用 loc和iloc 进行选取 

使用轴标签 (loc) 或整数索引 (iloc)

选取行和列的子集

In [122]:
data

one  two  three  four
Ohio        5    5      5     5
Colorado    5    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [125]:
data.loc['Colorado', ['two','three']]

two      5
three    6
Name: Colorado, dtype: int32

In [128]:
data

one  two  three  four
Ohio        5    5      5     5
Colorado    5    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [126]:
data.iloc[2, [3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [127]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [129]:
data.iloc[[1,2], [3,0,1]]

four  one  two
Colorado     7    5    5
Utah        11    8    9

In [130]:
data.loc[:'Utah','two']

Ohio        5
Colorado    5
Utah        9
Name: two, dtype: int32

In [132]:
data

one  two  three  four
Ohio        5    5      5     5
Colorado    5    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [137]:
print(type(data.three))
data.three

<class 'pandas.core.series.Series'>


Ohio         5
Colorado     6
Utah        10
New York    14
Name: three, dtype: int32

In [133]:
data.three>5

Ohio        False
Colorado     True
Utah         True
New York     True
Name: three, dtype: bool

In [135]:
data.iloc[:, :3]

one  two  three
Ohio        5    5      5
Colorado    5    5      6
Utah        8    9     10
New York   12   13     14

In [138]:
data.iloc[:,:3][data.three>5]

one  two  three
Colorado    5    5      6
Utah        8    9     10
New York   12   13     14

## 整数索引

In [139]:
import numpy as np

ser = pd.Series(np.arange(3))

ser

0    0
1    1
2    2
dtype: int32

In [141]:
# 出错 
ser[-1]

KeyError: -1

In [143]:
ser2 = pd.Series(np.arange(3.0), index =['a','b','c'])

ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [144]:
ser2[-1]

2.0

In [146]:
ser[:1]

0    0
dtype: int32

In [147]:
ser

0    0
1    1
2    2
dtype: int32

In [148]:
ser.loc[:1]

0    0
1    1
dtype: int32

In [149]:
ser.iloc[:1]

0    0
dtype: int32

## 算术运算和数据对齐

In [150]:

s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=['a', 'c', 'e', 'f', 'g'])

s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [151]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [152]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [154]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])

df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [155]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [156]:
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

如果 pd.DataFrame 对象相加， 没有公共的列或者行标签， 结果是 空 

In [158]:
df1 = pd.DataFrame({'A':[1,2]})

df2 = pd.DataFrame({'B':[3,4]})

df1

A
0  1
1  2

In [159]:
df2

B
0  3
1  4

In [160]:
df1-df2

A   B
0 NaN NaN
1 NaN NaN

## 在算数方法中 填充值

In [161]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list('abcde'))
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [163]:
df2.loc[1, 'b'] = np.nan

df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [164]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [165]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [166]:
1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

## DataFrame 和 Series 之间的运算

In [167]:
arr = np.arange(12).reshape((3,4))

arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [168]:
arr[0]

array([0, 1, 2, 3])

In [169]:
arr-arr[0]

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [170]:

frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])

frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [172]:
series = frame.iloc[0]

series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [173]:
frame- series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [174]:
series2 = pd.Series(range(3), index=['b','e','f'])

series2

b    0
e    1
f    2
dtype: int64

In [175]:
frame+series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [176]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [177]:
series3= frame['d']

series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [178]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [180]:
frame.sub(series3, axis='columns')

Ohio  Oregon  Texas  Utah   b   d   e
Utah     NaN     NaN    NaN   NaN NaN NaN NaN
Ohio     NaN     NaN    NaN   NaN NaN NaN NaN
Texas    NaN     NaN    NaN   NaN NaN NaN NaN
Oregon   NaN     NaN    NaN   NaN NaN NaN NaN

## 函数应用和映射

In [181]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah   -1.120332 -0.541364 -0.216484
Ohio    0.373755  1.106120  1.565379
Texas  -0.462116  0.349701 -0.071115
Oregon -1.082054  0.159009 -1.642791

In [182]:
np.abs(frame)

b         d         e
Utah    1.120332  0.541364  0.216484
Ohio    0.373755  1.106120  1.565379
Texas   0.462116  0.349701  0.071115
Oregon  1.082054  0.159009  1.642791

In [184]:
frame

b         d         e
Utah   -1.120332 -0.541364 -0.216484
Ohio    0.373755  1.106120  1.565379
Texas  -0.462116  0.349701 -0.071115
Oregon -1.082054  0.159009 -1.642791

将函数应用到 由各列或 各行所形成的一维数组上 

In [183]:
f = lambda x: x.max()- x.min()

In [185]:
frame.apply(f)  # 应用到每列 

b    1.494086
d    1.647484
e    3.208170
dtype: float64

In [186]:
frame.apply(f, axis='columns')   # 应用到每行

Utah      0.903848
Ohio      1.191624
Texas     0.811817
Oregon    1.801801
dtype: float64

In [187]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min','max'])

frame.apply(f)

b         d         e
min -1.120332 -0.541364 -1.642791
max  0.373755  1.106120  1.565379

## 排序和排名

In [188]:
obj = pd.Series(range(4), index=['d','a','b','c'])

obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [190]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)),
                    index=['three','one'],
                    columns=['d','a','b','c'])

frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [191]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [192]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

对 Series 进行排序， 使用 sort_values 方法 

In [193]:
obj = pd.Series([4,7,-3,2])

obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [194]:
obj = pd.Series([4, np.nan, 7, np.nan, -3,2])

obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

对 pd.DataFrame 进行排序 

In [195]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [196]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [197]:
frame.sort_values(by=['a','b'])


b  a
2 -3  0
0  4  0
3  2  1
1  7  1

### rank 部分没有看 不感兴趣

## 带有重复标签的轴索引 

In [198]:
obj = pd.Series(range(5), index=['a','a','b','b','c'])

obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [201]:
obj.index.is_unique

False

In [202]:
obj['a']

a    0
a    1
dtype: int64

In [203]:
obj['c']

4

In [204]:
df= pd.DataFrame(np.random.randn(4,3), index=['a','a','b','b'])

df

0         1         2
a -0.005987  0.795219 -1.420863
a  0.171019 -0.509866 -0.609391
b -0.188904 -1.942035  0.799662
b -0.507884 -1.137697  0.451641

In [205]:
df.loc['b']

0         1         2
b -0.188904 -1.942035  0.799662
b -0.507884 -1.137697  0.451641

## 唯一值， 值计数以及成员资格 

In [206]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [208]:
uniques = obj.unique()

uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [209]:
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [212]:
obj.values

array(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'], dtype=object)

In [211]:
pd.value_counts(obj.values, sort= False)

b    2
d    1
c    3
a    3
dtype: int64