# Chapter 4 NumPy Baiscs: Arrays and Vectorrized Computation 

- an idea of the performance difference 

In [1]:
import numpy as np 

In [2]:
my_arr = np.arange(1000000)
my_lsit = list(range(1000000))

In [3]:
%time for _ in range(10): my_arr2 = my_arr*2 

Wall time: 27.9 ms


In [4]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_lsit]

Wall time: 1.11 s


## 4.1 The NumPy ndarray: A Multidimensional Array Object 

In [5]:
data = np.random.randn(2,3)

data 

array([[ 0.56092256,  0.04572736,  1.41619496],
       [-1.5574798 ,  0.86690206, -0.66797618]])

In [6]:
data *10 
# all the elements have been multiplied by 10 

array([[  5.6092256 ,   0.45727356,  14.16194964],
       [-15.574798  ,   8.66902055,  -6.67976176]])

In [7]:
data + data 
# the corresponding values in each cell in the array have been added to each other

array([[ 1.12184512,  0.09145471,  2.83238993],
       [-3.1149596 ,  1.73380411, -1.33595235]])

In [8]:
# every array has a shape, 
# a tuple indicating the size of each dimension and a dtype 

print(data.dtype)

data.shape 

float64


(2, 3)

- Creating ndarrays 

In [9]:
data1 = [6, 7.5, 8, 0, 1]

data1

[6, 7.5, 8, 0, 1]

In [10]:
arr1 = np.array(data1)

arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [11]:
data2 = [[1,2,3,4],[5,6,7,8]]

arr2 = np.array(data2)

arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
# data2 a list of lists, has 2 dimensions 
# comfirm by ndim & shape 

print(arr2.ndim) 

arr2.shape 

2


(2, 4)

In [13]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [14]:
arr1.dtype 

dtype('float64')

In [15]:
arr2.dtype 

dtype('int32')

In [16]:
arr2.shape 

(2, 4)

In [17]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
a = np.zeros((3,6))
print(a)
a.shape 

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


(3, 6)

In [19]:
np.empty((2,3,2))
# 2 slices 3 rows 2 columns 

array([[[9.83547758e-312, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 8.30107618e-067]],

       [[1.39479328e-075, 6.75681348e+170],
        [3.11466439e+179, 9.60436728e-071],
        [1.64731907e+185, 5.69978888e-038]]])

In [20]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

- Data Types for adarrays 

In [21]:
arr1 = np.array([1,2,3], dtype = np.float64)
arr1

array([1., 2., 3.])

In [22]:
arr1.dtype 

dtype('float64')

In [23]:
arr2 = np.array([1,2,3], dtype = np.int32)
arr2.dtype 

dtype('int32')

Note: explicitly convert or cast an array from one dtype to another using ndarray’s
astype method:

In [24]:
arr = np.array([1,2,3,4,5])

arr.dtype 

dtype('int32')

In [25]:
float_arr = arr.astype(np.float64)
float_arr.dtype 

dtype('float64')

In [26]:
# cast the floating-point numbers to be of integer dtype
# the decimal part will be truncated 

arr = np.array([3.7,-1.2,-2.6,0.5,12.9,10.1])

arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [27]:
arr.dtype 

dtype('float64')

In [28]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [29]:
# use astype to convert strings to numeric form

numeric_strings = np.array(['1.25','-9.6','42'], dtype= np.string_)

numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [30]:
numeric_strings.astype(np.float64)

array([ 1.25, -9.6 , 42.  ])

In [31]:
# use another array's dtype attribute:

int_array = np.arange(10)
# calibers :口径；
calibers = np.array([0.22,.270,.357,.380,.44,.5], dtype = np.float64)
calibers.dtype 

dtype('float64')

In [32]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [33]:
print(int_array.astype(calibers.dtype).dtype)

float64


- Arithmetic with NumPy Arrays 

In [34]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [35]:
arr*arr 

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [36]:
arr - arr 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [37]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [38]:
arr **0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [39]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])

arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [40]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

- Basic Indexing and Slicing 

In [41]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
arr[5]

5

In [43]:
arr[5:8]

array([5, 6, 7])

In [44]:
arr[5:8] = 12 
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [45]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [46]:
# the mutations are reflected in the original array arr
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [47]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [48]:
# "bare" slice [:] will assign to all values in an array 

arr_slice[:] = 64 
arr 

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [49]:
"""
In a two-dimensional array, 
the elements at each index are no longer scalars but rather
one-dimensional
"""

arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

arr2d[2]

array([7, 8, 9])

In [50]:
# be seen as matrix 
arr2d[0][2]

3

In [51]:
# a comma-separated list of indices to select individual elements 
arr2d[0,2]

3

In [52]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [53]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
old_values = arr3d[0].copy()
arr3d[0] = 42

arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [55]:
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
arr3d[0]  = old_values

arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [57]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [58]:
arr3d[1,0]

array([7, 8, 9])

In [59]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [60]:
x[0]

array([7, 8, 9])

- Indexing with slices 

In [61]:
arr 

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [62]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [63]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
"""
you can pass multiple slices just like 
you can pass multiple indexes:
"""

arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [66]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
arr2d[1, :2]  # get 1-D result 

array([4, 5])

In [68]:
arr2d[:2, 2]  # get 1-D result 

array([3, 6])

In [69]:
arr2d 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
"""
a colon by itself means to take the entire axis,
so you can slice only higher dimensional axes by doing:
"""
arr2d[:, :1] # get 2-D result 

array([[1],
       [4],
       [7]])

In [71]:
arr2d 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
arr2d[:2, 1:] = 0 
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

- Boolean Indexing 

In [73]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names
data

array([[-0.17059465, -0.19456413,  0.17175458,  0.52752609],
       [ 0.45005224,  0.90156606, -2.10061664,  1.15357242],
       [ 0.39098991, -0.2677518 , -0.4764136 ,  0.95517043],
       [ 1.1300424 , -0.48830638, -0.22605479,  0.3059782 ],
       [-0.54650973, -0.35453174, -0.50217823, -1.36688635],
       [ 0.78274004, -0.10695538, -0.27106347, -1.51995296],
       [ 0.13880615,  0.00431648, -1.35187796, -0.76056763]])

In [74]:
names 

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [75]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [76]:
data[names == "Bob"]

array([[-0.17059465, -0.19456413,  0.17175458,  0.52752609],
       [ 1.1300424 , -0.48830638, -0.22605479,  0.3059782 ]])

In [77]:
data[names == "Bob", 2:] # get 2-D result 

array([[ 0.17175458,  0.52752609],
       [-0.22605479,  0.3059782 ]])

In [78]:
data[names == "Bob", 3] # get 1-D result 

array([0.52752609, 0.3059782 ])

In [79]:
names != "Bob"

array([False,  True,  True, False,  True,  True,  True])

In [80]:
data[~(names == "Bob")]

array([[ 0.45005224,  0.90156606, -2.10061664,  1.15357242],
       [ 0.39098991, -0.2677518 , -0.4764136 ,  0.95517043],
       [-0.54650973, -0.35453174, -0.50217823, -1.36688635],
       [ 0.78274004, -0.10695538, -0.27106347, -1.51995296],
       [ 0.13880615,  0.00431648, -1.35187796, -0.76056763]])

In [81]:
data[names != "Bob"]

array([[ 0.45005224,  0.90156606, -2.10061664,  1.15357242],
       [ 0.39098991, -0.2677518 , -0.4764136 ,  0.95517043],
       [-0.54650973, -0.35453174, -0.50217823, -1.36688635],
       [ 0.78274004, -0.10695538, -0.27106347, -1.51995296],
       [ 0.13880615,  0.00431648, -1.35187796, -0.76056763]])

In [82]:
data[names != "Bob"] == data[~(names == "Bob")]

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [83]:
cond = names == "Bob"

cond

array([ True, False, False,  True, False, False, False])

In [84]:
cond = names == "Bob"
print(cond)
data[~(names=="Bob")]

[ True False False  True False False False]


array([[ 0.45005224,  0.90156606, -2.10061664,  1.15357242],
       [ 0.39098991, -0.2677518 , -0.4764136 ,  0.95517043],
       [-0.54650973, -0.35453174, -0.50217823, -1.36688635],
       [ 0.78274004, -0.10695538, -0.27106347, -1.51995296],
       [ 0.13880615,  0.00431648, -1.35187796, -0.76056763]])

In [85]:
data[~cond]

array([[ 0.45005224,  0.90156606, -2.10061664,  1.15357242],
       [ 0.39098991, -0.2677518 , -0.4764136 ,  0.95517043],
       [-0.54650973, -0.35453174, -0.50217823, -1.36688635],
       [ 0.78274004, -0.10695538, -0.27106347, -1.51995296],
       [ 0.13880615,  0.00431648, -1.35187796, -0.76056763]])

In [86]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [87]:
data[mask]

array([[-0.17059465, -0.19456413,  0.17175458,  0.52752609],
       [ 0.39098991, -0.2677518 , -0.4764136 ,  0.95517043],
       [ 1.1300424 , -0.48830638, -0.22605479,  0.3059782 ],
       [-0.54650973, -0.35453174, -0.50217823, -1.36688635]])

In [88]:
data 

array([[-0.17059465, -0.19456413,  0.17175458,  0.52752609],
       [ 0.45005224,  0.90156606, -2.10061664,  1.15357242],
       [ 0.39098991, -0.2677518 , -0.4764136 ,  0.95517043],
       [ 1.1300424 , -0.48830638, -0.22605479,  0.3059782 ],
       [-0.54650973, -0.35453174, -0.50217823, -1.36688635],
       [ 0.78274004, -0.10695538, -0.27106347, -1.51995296],
       [ 0.13880615,  0.00431648, -1.35187796, -0.76056763]])

In [89]:
data[data<0] = 0 

data 

array([[0.        , 0.        , 0.17175458, 0.52752609],
       [0.45005224, 0.90156606, 0.        , 1.15357242],
       [0.39098991, 0.        , 0.        , 0.95517043],
       [1.1300424 , 0.        , 0.        , 0.3059782 ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.78274004, 0.        , 0.        , 0.        ],
       [0.13880615, 0.00431648, 0.        , 0.        ]])

In [90]:
names 

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [91]:
names != 'Joe'

array([ True, False,  True,  True,  True, False, False])

In [92]:
data[names != 'Joe'] = 7 

data 

array([[7.00000000e+00, 7.00000000e+00, 7.00000000e+00, 7.00000000e+00],
       [4.50052236e-01, 9.01566060e-01, 0.00000000e+00, 1.15357242e+00],
       [7.00000000e+00, 7.00000000e+00, 7.00000000e+00, 7.00000000e+00],
       [7.00000000e+00, 7.00000000e+00, 7.00000000e+00, 7.00000000e+00],
       [7.00000000e+00, 7.00000000e+00, 7.00000000e+00, 7.00000000e+00],
       [7.82740039e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.38806146e-01, 4.31648471e-03, 0.00000000e+00, 0.00000000e+00]])

- Fancy Indexing 

In [93]:
arr = np.empty((8,4))

for i in range(8):
    arr[i] = i 
    
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [94]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [96]:
# 0  1   2  3  4  5   6  7 
# -8 -7 -6 -5 -4 -3  -2 -1

arr[[-3, -5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [97]:
"""
Passing multiple index arrays does 
something slightly different;
it selects a onedimensional array of elements
corresponding to each tuple of indices:
"""

arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [98]:
arr[[1,5,7,2],[0,3,1,2]]

# (1,0) (5,3) (7,1) (2,2)

array([ 4, 23, 29, 10])

In [ ]:
"""
Regardless of how many dimensions the array has 
(here, only 2), the result of fancy indexing is
always one-dimensional
"""

In [99]:
arr[[1,5,7,2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [100]:
arr[[1,5,7,2]][:, [0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

- Transposing Arrays and Swapping Axes 

In [101]:
arr = np.arange(15).reshape((3,5))

arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [102]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [103]:
arr = np.random.randn(6,3)
arr

array([[-0.04324255,  1.86684053, -0.69690736],
       [-0.48698041, -0.64463378, -0.36049869],
       [ 0.7531071 , -0.18183411, -0.19623289],
       [ 0.02995748, -0.74546963,  0.06145198],
       [-1.31896249,  0.7360558 ,  0.06417895],
       [ 0.20993608,  0.48122495, -0.5620268 ]])

In [104]:
np.dot(arr.T, arr)
# (3,6)*(6,3) = (3,3)

array([[ 2.59082281, -0.79587938, -0.14289091],
       [-0.79587938,  5.26279047, -1.30197605],
       [-0.14289091, -1.30197605,  0.97791593]])

In [105]:
arr = np.arange(16).reshape((2,2,4))

arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [106]:
arr.transpose((1,0,2))  # 

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [107]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [108]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])