# Chapter 4 NumPy Baiscs: Arrays and Vectorrized Computation 

## 4.2 Universal Functions: Fast Element-Wise Array Functions

In [1]:
import numpy as np 

In [2]:
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [4]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [5]:
x = np.random.randn(8)
x

array([ 0.70387981, -0.83983566,  0.83765662,  2.43395221, -1.25731766,
       -0.26919818,  2.20043664,  1.35644002])

In [6]:
y = np.random.randn(8)
y

array([ 0.85872954, -0.15157647, -2.81213469, -1.96081847,  1.89034923,
        0.80985912, -1.0860906 ,  0.46132348])

In [7]:
np.maximum(x,y)

array([ 0.85872954, -0.15157647,  0.83765662,  2.43395221,  1.89034923,
        0.80985912,  2.20043664,  1.35644002])

In [8]:
arr = np.random.randn(7)*5 
arr

array([-1.61668858,  4.48349829,  3.23437506, -5.54804721,  1.98898359,
       -9.58662786,  2.31450149])

In [9]:

remainder, whole_part = np.modf(arr)
remainder

array([-0.61668858,  0.48349829,  0.23437506, -0.54804721,  0.98898359,
       -0.58662786,  0.31450149])

In [10]:
whole_part

array([-1.,  4.,  3., -5.,  1., -9.,  2.])

In [11]:
arr

array([-1.61668858,  4.48349829,  3.23437506, -5.54804721,  1.98898359,
       -9.58662786,  2.31450149])

In [12]:
np.sqrt(arr)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([       nan, 2.11742728, 1.79843684,        nan, 1.4103133 ,
              nan, 1.52134858])