# An Essential Guide to Numpy for Machine Learning in Python

https://becominghuman.ai/an-essential-guide-to-numpy-for-machine-learning-in-python-5615e1758301

## 1. Creating a Vector

In [1]:
# load the library
import numpy as np 

In [2]:
# create a vector as a row 
vector_row = np.array([1,2,3])
vector_row

array([1, 2, 3])

In [3]:
# create vector asa column 

vector_column = np.array([[1],[2],[3]])
vector_column

array([[1],
       [2],
       [3]])

## 2. Create a Matrix 

In [4]:
matrix = np.array([[1,2,3],[4,5,6]])
matrix

array([[1, 2, 3],
       [4, 5, 6]])

## 3. Creating a Sparse Matrix

In [5]:
"""
Sparse Matrices store only non zero elements 
and assume all other values will be zero,
leading to significant computational savings.
"""

matrix = np.array([[0,0],[0,1],[3,0]])
matrix

array([[0, 0],
       [0, 1],
       [3, 0]])

In [6]:
# #Create Compressed Sparse Row(CSR) matrix
import scipy.sparse 
matrix_sparse = scipy.sparse.csr_matrix(matrix)
matrix_sparse

<3x2 sparse matrix of type '<class 'numpy.int32'>'
	with 2 stored elements in Compressed Sparse Row format>

In [7]:
# csr_matrix example
import numpy as np
from scipy.sparse import csr_matrix

row = np.array([0, 0, 1, 2, 2, 2])
col = np.array([0, 2, 2, 0, 1, 2])
data = np.array([1, 2, 3, 4, 5, 6])
a = csr_matrix((data, (row, col)), shape=(3, 3)).toarray()

print(a)

[[1 0 2]
 [0 0 3]
 [4 5 6]]


## 4.Selecting Elements

In [8]:
# #Create a vector as a Row
vector_row = np.array([1,2,3,4,5,6])

# #Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
#Select 3rd element of Vector

vector_row[2]

3

In [10]:
# select 2nd row and 2nd column 

print(matrix[1][1])

print(matrix[1,1]) 

matrix[1][1] == matrix[1,1]

5
5


True

In [11]:
# select all elements of a vector 
print(vector_row[:])

vector_row

[1 2 3 4 5 6]


array([1, 2, 3, 4, 5, 6])

In [12]:
# select everything up to and including the 3rd element 

vector_row[:3]

array([1, 2, 3])

In [13]:
# select the everything after the 3rd element 

vector_row[3:]

array([4, 5, 6])

In [14]:
# select the last element 
print(vector_row[-1])

6


In [15]:
# select the first 2 rows and all the columns of the matrix

matrix[:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
# select all rows and the 2nd column of the matrix

matrix[:, 1:2]
# Note: get 2 dim

array([[2],
       [5],
       [8]])

## 5. Describing a Matrix

In [17]:
# create a matrix 
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
# view the number of rows and columns 
matrix.shape 

(3, 3)

In [19]:
# view the number of elements 
# (rows*columns)
matrix.size 

9

In [20]:
# view the number of dim 
matrix.ndim

2

## 6. Applying operations to elements 

In [21]:
# create a matrix 
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
# create a function that adds 100 to sth 

add_100 = lambda i: i+100 


In [23]:
# convert it into a vectorized function 

vectorized_add_100 = np.vectorize(add_100)
vectorized_add_100

In [24]:
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [25]:
# add 100 directly 
print(matrix)

matrix+100

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

## 7. Finding the max and min values 

In [26]:
# create a matrix 

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
# return the min element 
np.min(matrix)

1

In [28]:
# return the max element 
np.max(matrix)

9

In [29]:
# find the max element in each row 
print(matrix)
np.max(matrix, axis=1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([3, 6, 9])

## 8.  Calculating Average, Variance and Standard deviation

In [30]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
# mean
np.mean(matrix)

5.0

In [32]:
# standard dev.
np.std(matrix)

2.581988897471611

In [33]:
# variance 
np.var(matrix)

6.666666666666667

## 9. Reshaping Arrays 

In [34]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
# reshape 
matrix.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [36]:
# -1 says 
matrix.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [37]:
# -1 says as many columns as neededd and 1 row 

matrix.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [39]:
# if we provide only 1 value reshape would return 
# a 1-d array 

matrix.reshape(9)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
# use the flatten method to convert a 
# matrix to array 

matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## 10. Transposing a vector or a Matrix

In [42]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

matrix.T

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## 11. Finding the Determinant and Rank of a Matrix

In [44]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

np.linalg.det(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


0.0