# 1. Chapter Vectors, Matrices, and Arrays

## 1.1 Creating a Vector

In [2]:
import numpy as np 

vector_row=np.array([1,2,3])

vector_row

array([1, 2, 3])

In [3]:
vector_col= np.array([[1],
                     [2],
                     [3]])

vector_col

array([[1],
       [2],
       [3]])

## 1.2 Creating a Matric 

In [4]:
matrix_object = np.mat([[1,2],
                       [1,2],
                       [1,2]])

matrix_object

matrix([[1, 2],
        [1, 2],
        [1, 2]])

## 1.3 Creating a Sparse Matrix

In [9]:
from scipy import sparse 

matrix=np.array([[0,0],
                [0,1],
                [3,0]])
matrix

matrix_sparse=sparse.csr_matrix(matrix)

matrix_sparse

<3x2 sparse matrix of type '<class 'numpy.int32'>'
	with 2 stored elements in Compressed Sparse Row format>

In [14]:
# load libraries
import numpy as np
from scipy import sparse

# create a matrix
matrix = np.array([[0, 0],
                  [0, 1],
                  [3, 0]])

# create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)

print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [13]:

# view sparse matrix
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [15]:
# create larger matrix
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                         [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

# create compressed sparse row (CSR) matrix
matrix_large_sparse = sparse.csr_matrix(matrix_large)

# view original sparse matrix
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


## 1.4 Selected Elements

In [16]:
# load library
import numpy as np

# create row vector
vector = np.array([1, 2, 3, 4, 5, 6])

# create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# select the third element of vector
vector[2]

3

In [17]:

# select second row, second column
matrix[1,1]

5

In [18]:
# Select all elements of a vector
vector[:]

array([1, 2, 3, 4, 5, 6])

In [19]:
# select everything up to and including the third element
vector[:3]

array([1, 2, 3])

In [20]:

# select the last element
vector[-1]

6

In [22]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
# select the first two rows and all columns of a matrix
matrix[:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
# select all rows and the second column
matrix[:,1:2]

array([[2],
       [5],
       [8]])

## 1.5 Describing a Matrix

In [25]:
# load library
import numpy as np

# create matrix
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

# view number of rows and columns
matrix.shape

(3, 4)

In [26]:
# view number of elements (rows * columns)
matrix.size

12

In [27]:
# view number of dimensions
matrix.ndim

2

## 1.6 Applying Operations to Elements

In [28]:

# load library
import numpy as np

# create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# create function that adds 1000 to something
add_1000 = lambda i: i + 1000

# create vectorized function
vectorized_add_1000 = np.vectorize(add_1000)

# apply function to all elementsin matrix
vectorized_add_1000(matrix)

array([[1001, 1002, 1003],
       [1004, 1005, 1006],
       [1007, 1008, 1009]])

In [29]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
# add 1000 to all elements
matrix + 1000

array([[1001, 1002, 1003],
       [1004, 1005, 1006],
       [1007, 1008, 1009]])

### Finding Maximum and Minimum Values

In [31]:
# load library
import numpy as np

# create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# rreturn maximum element
np.max(matrix)

9

In [32]:
# return minimum element
np.min(matrix)

1

In [33]:
# find maximum element in each column
np.max(matrix, axis=0)

array([7, 8, 9])

In [34]:
# find maximum element in each row
np.max(matrix, axis=1)

array([3, 6, 9])

## 1.8 Calculating the Average, Variance, and Standard Deviation

In [35]:
# load library
import numpy as np

# create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# return mean
np.mean(matrix)

5.0

In [36]:
# return variance
np.var(matrix)

6.666666666666667

In [37]:
# return standard deviation
np.std(matrix)

2.5819888974716112

In [38]:
# find the mean value in each column
np.mean(matrix, axis=0)

array([ 4.,  5.,  6.])

## 1.9 Reshaping Arrays

In [39]:
# load library
import numpy as np

# create 4x3 matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

# reshape matrix into 2x6 matrix
matrix.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [40]:
matrix.size

12

In [41]:
matrix.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [42]:
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## 1.10 Transposing a Vector or Matrix

In [43]:
# load library
import numpy as np

# create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# transpose matrix
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [44]:
# transpose vector
np.array([1, 2, 3, 4, 5, 6]).T

array([1, 2, 3, 4, 5, 6])

In [45]:
# transpose row vector
np.array([[1, 2, 3, 4, 5, 6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

## 1.11 Flattening a Matrix

In [46]:

# load library
import numpy as np

# create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# flatten matrix
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
matrix.reshape(1, -1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

## 1.12 Finding the Rank of a Matrix

In [49]:

# load library
import numpy as np

# create matrix
matrix = np.array([[1, 1, 1],
                   [1, 1, 10],
                   [1, 1, 15]])

# return matrix rank
np.linalg.matrix_rank(matrix)

2

## 1.13 Calculating the Determinant

In [50]:
# load library
import numpy as np

# create matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

# return the determinant of matrix
np.linalg.det(matrix)

0.0

## 1.14 Getting the Diagonal of a Matrix

In [51]:
# load library
import numpy as np

# create matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

# return diagonal elements
matrix.diagonal()

array([1, 4, 9])

In [52]:
# return diagonal one above the main diagonal
matrix.diagonal(offset=1)

array([2, 6])

## 1.15 Calculating the Trace of a Matrix

In [53]:
# load library
import numpy as np

# create matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

# return trace
matrix.trace()

14

## 1.16 Finding Eigenvalues and Eigenvectors

In [54]:
# load library
import numpy as np

# create matrix
matrix = np.array([[1, -1, 3],
                   [1, 1, 6],
                   [3, 8, 9]])

# calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

# view eigenvalues
eigenvalues

array([ 13.55075847,   0.74003145,  -3.29078992])

In [55]:

# view eigenvectors
eigenvectors

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

## 1.17 Calculating Dot Products

In [56]:
# load library
import numpy as np

# create two vectors
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

# calculate dot product
np.dot(vector_a, vector_b)

32

In [58]:
# calculate dot product
vector_a @ vector_b

32

## 1.18 Adding and Subtracting Matricies

In [59]:

# load library
import numpy as np

# create matricies
matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])

matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])

# add two matricies
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [60]:

# subtract two matrices
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [62]:
# add two matricies
matrix_a + matrix_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

## 1.19 Multiplying Matricies

In [63]:

# load library
import numpy as np

# create matrices
matrix_a = np.array([[1, 1],
                     [1, 2]])

matrix_b = np.array([[1, 3],
                     [1, 2]])

# multiply two matrices
np.dot(matrix_a, matrix_b)

array([[2, 5],
       [3, 7]])

In [64]:
# multiply two matrices
matrix_a @ matrix_b

array([[2, 5],
       [3, 7]])

##  1.20 Inverting a Matrix

In [65]:

# load library
import numpy as np

# create matrix
matrix = np.array([[1, 4],
                  [2, 5]])

# calculate inverse of matrix
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [66]:
matrix @ np.linalg.inv(matrix)

array([[ 1.,  0.],
       [ 0.,  1.]])

## 1.21 Generating Random Values

In [67]:

# load library
import numpy as np

# set seed
np.random.seed(0)

# generate three random floats between 0.0 and 1.0
np.random.random(3)

array([ 0.5488135 ,  0.71518937,  0.60276338])

In [69]:

# genereate three random integers between 1 and 10
np.random.randint(0, 11, 3)

array([3, 5, 2])

In [70]:
# draw three numbers from a normal distribution with mean 0.0
# and standard deviation of 1.0
np.random.normal(0.0, 1.0, 3)

array([ 0.95008842, -0.15135721, -0.10321885])

In [71]:
# draw three numbers from a logistic distribution with mean 0.0 and scale of 1.0
np.random.logistic(0.0, 1.0, 3)

array([ 1.33535502,  0.1157086 ,  0.27387744])

In [72]:
# draw three numbers greater than or equal to 1.0 and less than 2.0
np.random.uniform(1.0, 2.0, 3)

array([ 1.92559664,  1.07103606,  1.0871293 ])